### ISSUE TITLE
Please consider remove Jackson from ktor-openapi-generator

### ISSUE THREAD

**Issue by cuong0993** [LukasForst/ktor-plugins#21]
Hi Lukas,

Can you consider removing Jackson from your library? (Jackson is currently used in testing in the library)
https://github.com/LukasForst/ktor-openapi-generator

I think converting map to JSON in the library can be done manually like this.
https://github.com/Kotlin/kotlinx.serialization/issues/296#issuecomment-1132714147.

Removing helps users choose multiple option alternatives to Jackson.
I am trying to use io.ktor:ktor-serialization-kotlinx-json instead of Jackson but the ktor-openapi-generator did not work with io.ktor:ktor-serialization-kotlinx-json.

**Comment by LukasForst** [comment]
Hi,
please see https://github.com/papsign/Ktor-OpenAPI-Generator/issues/42 for `kotlinx.serialization` support. I'm not using kotlinx, so I can't directly say how hard is that or not. However, I'm open to PRs that would make this project more generic!
